### ISSUE TITLE
[Releases]

### ISSUE THREAD

**Issue by alosarjos** [juanmanuelcarrera/feelmusic#43]
Tengo el código de Travis para publicar APKs de Android en las releases:

Pero tienes que hacer unos pasos:

Descargar el CLI de Travis con brew: brew install travis

En el directorio del proyecto lanzar:

travis setup releases

Seguir los pasos. Lo más importante es que te pedirá tu cuenta de GitHub para conseguir una clave privada con la que hacer push al release. Te preguntará si quieres cifrarla, dices que si.

Te modificará el archivo de travis, pero tienes que tocarlo a mano y básicamente poner esto al final de las instrucciones para Android pero con tu código secreto. Si prefieres genera el código secreto ( Que va cifrado para que se pueda poner en un repo público sin problemas) y me lo pasas y hago una pr

```
deploy:
      skip_cleanup: true
      provider: releases
      api_key:
        secure: "SECRET_CODE"
      file: "$TRAVIS_BUILD_DIR/android/app/build/outputs/apk/app-release-unsigned.apk"
      on:
        repo: juanmanuelcarrera/feelmusic
        tags: true
```
